use_tpu: True
train_batch_size: 1024
train_steps: 8000000
eval_batch_size: 1024
iterations_per_loop: 100
num_shards: 8
eval_total_size: 0
train_steps_per_eval: 2000
min_eval_interval: 180
learning_rate: 0.165
depth_multiplier: 1.0
optimizer: 'RMS'
num_classes: 1001
use_fused_batchnorm: True
moving_average: True
learning_rate_decay: 0.94
learning_rate_decay_epochs: 3
use_logits: True
clear_update_collections: True
transpose_enabled: False
num_train_images: 1281167
num_eval_images: 50000
