# ---------- TRAINING PARAMETERS ----------
# AutoAugment achieves best results when trained for long and when not using a pretrained
# checkpoint for the backbone.
# Right now the code uses a pretrained checkpoint, but a future version will change this.
# To train the ResNet 101 or ResNet 200 version, simply change the 'resnet_depth' to 101 or 200.
# Expected accuracy on ResNet 50 with using autoaugment: 38.0
# Expected accuracy on ResNet 50 without using autoaugment: 36.4
train:
  total_steps: 277200
  learning_rate:
    init_learning_rate: 0.08
    learning_rate_levels: [0.008, 0.0008]
    learning_rate_steps: [220000, 258700]

resnet:
  resnet_depth: 50

retinanet_parser:
  aug_policy: 'v0'
  aug_scale_min: 0.8
  aug_scale_max: 1.2
