augment_name: randaugment
base_learning_rate: 0.1
data_format: channels_last
drop_connect_rate: 0.1
dropout_rate: 0.4
eval_batch_size: 200
image_size: 320
label_smoothing: 0.1
momentum: 0.9
num_eval_images: 50000
num_label_classes: 1000
num_train_images: 1281167
precision: bfloat16
randaug_magnitude: 15
randaug_num_layers: 2
replace_stem_max_pool: True
resnet_depth: 420
resnetd_shortcut: True
se_ratio: 0.25
train_batch_size: 4096
train_steps: 109475
transpose_input: True
use_resnetd_stem: True
use_tpu: True
weight_decay: 4.0e-05
moving_average_decay: 0.9999
bn_momentum: 0
