init_learning_rate: 0.00005  # with 0.005 the network is unstable
loss: 'cross_entropy'
train_batch_size: 8
eval_batch_size: 1
input_partition_dims: [1,16,1,1,1]
use_index_label_in_train: true

input_image_size: [256,256,256]
label_dtype: 'float32'
