# SpineNet-96 + RetinaNet:
# - 46.7% mAP with init_drop_connect_rate null, activation 'relu', total_steps 162050, learning_rate_steps [148160, 157420]
# - 48.5% mAP with init_drop_connect_rate: 0.2, activation: 'swish', total_steps 231500, learning_rate_steps [217610, 226870]

architecture:
  backbone: 'spinenet'
  multilevel_features: 'identity'
train:
  total_steps: 231500
  train_batch_size: 256
  learning_rate:
    warmup_steps: 2000
    init_learning_rate: 0.28
    learning_rate_levels: [0.028, 0.0028]
    learning_rate_steps: [217610, 226870]
  l2_weight_decay: 0.00004
  gradient_clip_norm: 10.0
batch_norm_activation:
  use_sync_bn: true
  activation: 'swish'
spinenet:
  model_id: '96'
  init_drop_connect_rate: 0.2
anchor:
  anchor_size: 3.0
retinanet_parser:
  output_size: [1024, 1024]
  aug_scale_min: 0.5
  aug_scale_max: 2.0
