# SpineNet49-MBConv + RetinaNet with swish. 28.5% mAP.
architecture:
  backbone: 'spinenet_mbconv'
  multilevel_features: 'identity'
train:
  total_steps: 277800
  train_batch_size: 256
  learning_rate:
    type: 'step'
    init_learning_rate: 0.28
    learning_rate_levels: [0.028, 0.0028]
    learning_rate_steps: [263910, 273170]
  l2_weight_decay: 0.00003
batch_norm_activation:
  use_sync_bn: true
  activation: 'swish'
retinanet_head:
  retinanet_head_num_filters: 48
  use_separable_conv: true
spinenet_mbconv:
  filter_size_scale: 1.0
  block_repeats: 1
  endpoints_num_filters: 48
anchor:
  anchor_size: 3.0
retinanet_parser:
  output_size: [384, 384]
  aug_scale_min: 0.5
  aug_scale_max: 2.0
