# ---------- MODEL PARAMETERS -------------
resnet_depth: 50
num_cores: 8
# ---------- TRAINING PARAMETERS ----------
train_batch_size: 64
init_learning_rate: 0.08
warmup_learning_rate: 0.0067
warmup_steps: 500
learning_rate_levels: [0.008, 0.0008]
learning_rate_steps: [15000, 20000]
total_steps: 22500
precision: 'bfloat16'
# ---------- EVAL PARAMETERS --------------
eval_batch_size: 8
eval_samples: 5000
num_steps_per_eval: 2500
